apiVersion: v1 
kind: Pod
metadata: 
  name: myapp-pod
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: nginx-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: ClusterIP
